name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Build and test with Rake
      env:
        IREDMAIL_DOMAIN: ${{ secrets.IREDMAIL_DOMAIN }}
        IREDMAIL_USER: ${{ secrets.IREDMAIL_USER }}
        IREDMAIL_PASSWORD: ${{ secrets.IREDMAIL_PASSWORD }}
        IREDMAIL_SUBJECT: ${{ secrets.IREDMAIL_SUBJECT }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
    - uses: actions/setup-node@v1
    - name: Check markdown files using `markdownlint`
      run: |
        npm install -g markdownlint-cli
        markdownlint *.md
